doctrine_migrations:
    dir_name: '%kernel.root_dir%/Migrations'
    namespace: App\Migrations
    table_name: migration_versions
    name: 'Application Migrations'
    organize_migrations: BY_YEAR_AND_MONTH
    all_or_nothing: true
    custom_template: "%kernel.project_dir%/src/Migrations/migration.tpl"
