framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    templating:
        engines: ['twig']
        form:
            resources:
                - ':form/type/extended_date.html.twig'
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
