fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /user

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /writer

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /writer
