imports:
    - { resource: sonata.services.yaml }

parameters:
    locale: '%env(LOCALE)%'
    sender_address: "%env(SENDER_ADDRESS)%"
    sender_name: "%env(SENDER_NAME)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{Admin/Type,DependencyInjection,DataFixtures,Entity,Migrations,Tests,Twig,Kernel.php}'
    App\Admin\Type\:
        resource: '../src/Admin/Type'
        tags: [form.type]
    App\Admin\Type\OwnerAware\:
        resource: '../src/Admin/Type/OwnerAware'
        calls:
            - ['setTokenStorage', ['@security.token_storage']]
            - ['setRouter', ['@router']]
        tags: [form.type]
    App\Controller\:
        resource: '../src/Controller'
        calls:
            - ['setLogger', ['@logger']]
        tags: ['controller.service_arguments']
    App\Controller\CRUD\:
        resource: '../src/Controller/CRUD'
        calls:
            - ['setLogger', ['@logger']]
            - ['setTokenStorage', ['@security.token_storage']]
        tags: ['controller.service_arguments']
    App\DataFixtures\:
        resource: '../src/DataFixtures'
        arguments:
            - '@translator'
            - '@fos_user.user_manager'
        tags: ['doctrine.fixture.orm']
    App\Entity\Repository\:
        resource: '../src/Entity/Repository'
    App\Twig\:
        resource: '../src/Twig'
        calls:
            - ['setTranslator', ['@translator']]
            - ['setRouter', ['@router']]
        tags: [twig.extension]

    ##### Types

    App\Admin\Type\SecurityRolesType:
        class: App\Admin\Type\SecurityRolesType
        calls:
            - [setSecurityRoles, ['%security.role_hierarchy.roles%']]
        tags: [form.type]

    ##### Test only
    test.processor.image:
        alias: App\Processor\ImageProcessor
        public: true
