services:

    ##### Shared group
    sonata.admin.character_type:
        class: App\Admin\CharacterTypeAdmin
        arguments: [~, App\Entity\CharacterType, App\Controller\CRUD\CharacterController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.character_type, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.country:
        class: App\Admin\CountryAdmin
        arguments: [~, App\Entity\Country, App\Controller\CRUD\CountryController]
        calls:
            - [setRepository, ['@App\Entity\Repository\CountryRepository']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.country, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.gender:
        class: App\Admin\GenderAdmin
        arguments: [~, App\Entity\Gender, App\Controller\CRUD\GenderController]
        calls:
            - [setRepository, ['@App\Entity\Repository\CountryRepository']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.gender, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.intelligence_quotient:
        class: App\Admin\IntelligenceQuotientAdmin
        arguments: [~, App\Entity\IntelligenceQuotient, App\Controller\CRUD\IntelligenceQuotientController]
        calls:
            - [setRepository, ['@App\Entity\Repository\IntelligenceQuotientRepository']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.intelligence_quotient, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.location_type:
        class: App\Admin\LocationTypeAdmin
        arguments: [~, App\Entity\LocationType, App\Controller\CRUD\LocationTypeController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.location_type, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.profession:
        class: App\Admin\ProfessionAdmin
        arguments: [~, App\Entity\Profession, App\Controller\CRUD\ProfessionController]
        calls:
            - [setRepository, ['@App\Entity\Repository\IntelligenceQuotientRepository']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.profession, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.religion:
        class: App\Admin\ReligionAdmin
        arguments: [~, App\Entity\Religion, App\Controller\CRUD\ReligionController]
        calls:
            - [setRepository, ['@App\Entity\Repository\ReligionRepository']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.religion, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.sexuality:
        class: App\Admin\SexualityAdmin
        arguments: [~, App\Entity\Sexuality, App\Controller\CRUD\SexualityController]
        calls:
            - [setRepository, ['@App\Entity\Repository\SexualityRepository']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.sexuality, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.temperament:
        class: App\Admin\TemperamentAdmin
        arguments: [~, App\Entity\Temperament, App\Controller\CRUD\TemperamentController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.temperament, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.zodiac:
        class: App\Admin\ZodiacAdmin
        arguments: [~, App\Entity\Zodiac, App\Controller\CRUD\ZodiacController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.zodiac, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    ##### Project group

    sonata.admin.project:
        class: App\Admin\ProjectAdmin
        arguments: [~, App\Entity\Project, App\Controller\CRUD\ProjectController]
        calls:
            - [setTokenStorage, ['@security.token_storage']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: project, label: menu.item.project, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.chapter:
        class: App\Admin\ChapterAdmin
        arguments: [~, App\Entity\Chapter, App\Controller\CRUD\ChapterController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: project, label: menu.item.chapter, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.scene:
        class: App\Admin\SceneAdmin
        arguments: [~, App\Entity\Scene, App\Controller\CRUD\SceneController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: project, label: menu.item.scene, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true


    ##### Writing group


    sonata.admin.character:
        class: App\Admin\CharacterAdmin
        arguments: [~, App\Entity\Character, App\Controller\CRUD\CharacterController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: writing, label: menu.item.character, label_translator_strategy: "sonata.admin.label.strategy.native" }
        calls:
            - ['setZodiacRepository', ['@App\Entity\Repository\ZodiacRepository']]
        public: true

    sonata.admin.concept:
        class: App\Admin\ConceptAdmin
        arguments: [~, App\Entity\Concept, App\Controller\CRUD\ConceptController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: writing, label: menu.item.concept, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.key_item:
        class: App\Admin\KeyItemAdmin
        arguments: [~, App\Entity\KeyItem, App\Controller\CRUD\KeyItemController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: writing, label: menu.item.key_item, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.location:
        class: App\Admin\LocationAdmin
        arguments: [~, App\Entity\Location, App\Controller\CRUD\LocationController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: writing, label: menu.item.location, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

