services:
    sonata.admin.intelligence_quotient:
        class: App\Admin\IntelligenceQuotientAdmin
        arguments: [~, App\Entity\IntelligenceQuotient, ~]
        calls:
            - [setRepository, ['@App\Entity\Repository\IntelligenceQuotientRepository']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.intelligence_quotient, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.profession:
        class: App\Admin\ProfessionAdmin
        arguments: [~, App\Entity\Profession, ~]
        calls:
            - [setRepository, ['@App\Entity\Repository\IntelligenceQuotientRepository']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.profession, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.religion:
        class: App\Admin\ReligionAdmin
        arguments: [~, App\Entity\Religion, ~]
        calls:
            - [setRepository, ['@App\Entity\Repository\ReligionRepository']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.religion, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.sexuality:
        class: App\Admin\SexualityAdmin
        arguments: [~, App\Entity\Sexuality, ~]
        calls:
            - [setRepository, ['@App\Entity\Repository\SexualityRepository']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.sexuality, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.temperament:
        class: App\Admin\TemperamentAdmin
        arguments: [~, App\Entity\Temperament, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.temperament, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    sonata.admin.zodiac:
        class: App\Admin\ZodiacAdmin
        arguments: [~, App\Entity\Zodiac, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: shared, label: menu.item.zodiac, label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true
